package com.yihengliu.demo.common.model;

import com.yihengliu.demo.common.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article().dao();

	public Auser getAuser() {
		return Auser.dao.findById(get("uid"));
	}
}
