package com.yihengliu.demo.common.model;

import com.yihengliu.demo.common.model.base.BaseAuser;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Auser extends BaseAuser<Auser> {
	public static final Auser dao = new Auser().dao();

	public List<Article> getArticles() {
		return Article.dao.find("select * from article where uid = ?", 2);
	}
}
