package com.yihengliu.demo.common.model;

import com.yihengliu.demo.common.model.base.BaseRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Record extends BaseRecord<Record> {
	public static final Record dao = new Record().dao();
}
